run_name: "baseline"
seed: 43

# You need to provide models in ascending order by parameter count for MESS+ to work correctly.
model_zoo:
  Qwen/Qwen2-0.5B-Instruct:
    category: "small"
    gpu_indices: [0]
    max_seq_len: 2048
    gpu_memory_utilization: 0.08
    quantization: null
  Qwen/Qwen2-7B-Instruct:
    category: "medium"
    gpu_indices: [0]
    max_seq_len: 2048
    gpu_memory_utilization: 0.20
    quantization: null
  Qwen/Qwen2.5-32B-Instruct:
    category: "large"
    gpu_indices: [0]
    max_seq_len: 2048
    gpu_memory_utilization: 0.70
    quantization: "bitsandbytes"

classifier_model:
  model_id: "answerdotai/ModernBERT-base"
  epochs: 3
  learning_rate: 0.0999
  weight_decay: 0.01
  momentum: 0.9
  batch_size: 128
  max_length: 64
  warmup_ratio: 0.1
  threshold: 0.5
  dropout_rate: 0.1
  freeze_bert_layers: true
  memory_size: 0
  memory_strategy: random # This only works when memory_size > 0
  reset_optimizer: false
  regularization_lambda: 0.0
  gpu_index: 0
  disable_tqdm: false
  # Path uses the "classifier" folder as root. Alternatively you can specify an absolute path.
  checkpoint_path: "checkpoints/lambada_standard"
  use_pretrained_classifier: true
  scoring_method: raw
  validation_dataset_size: 0.1
  generate_training_dataset: false
  write_training_dataset_to_disk: false

algorithm:
  alpha_values: [0.2,0.3,0.4,0.6,0.7,0.8]
  alpha: 0.75
  c: 1
  V: 0.01

lm_eval:
  # The run name will be the first benchmark in the list below.
  benchmarks: ["lambada_standard"]
  num_repeats: 1
  limit_num_samples: null
  # TODO: Make sure we disable eager mode for the actual experiments to be as energy efficient as possible.
  enforce_eager: true
  write_to_disk: false
